on:
  push:
    branches:
      - 'main'

name: Deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: documentation

    strategy:
      matrix:
        ruby-version: [3.0]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: gems-${{ runner.os }}-${{ env.ruby-version }}-${{ hashFiles('**/Gemfile.lock') }}

      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Set up widdershins
        run: |
          npm install -g widdershins
          mkdir -p source/includes/partials_admin_metrics
          mkdir -p source/includes/partials_common_apis
          mkdir -p source/includes/partials_open_insurance

      - name: Run widdershins for admin metrics and status outage
        run: |
          widdershins source/swagger/admin_metrics.yaml \
          -o source/includes/partials_admin_metrics/_admin_metrics.md.erb \
          --language_tabs "javascript:JavaScript:request" "python:Python:request" "java:Java::request" \
          --omitHeader --summary --httpsnippet

          widdershins source/swagger/status_outage.yaml \
          -o source/includes/partials_common_apis/_status_outage.md.erb \
          --language_tabs "javascript:JavaScript:request" "python:Python:request" "java:Java::request" \
          --omitHeader --summary --httpsnippet

      # Fase 1
      - name: Run widdershins for "fase 1"
        run: |
          widdershins source/swagger/open_data_channels.yaml \
          -o source/includes/partials_open_insurance/_open_data_channels.md.erb \
          --language_tabs "javascript:JavaScript:request" "python:Python:request" "java:Java::request" \
          --omitHeader --summary --httpsnippet

          widdershins source/swagger/open_data_products_services.yaml \
          -o source/includes/partials_open_insurance/_open_data_products_services.md.erb \
          --language_tabs "javascript:JavaScript:request" "python:Python:request" "java:Java::request" \
          --omitHeader --summary --httpsnippet

      - uses: actions/cache@v1
        with:
          path: build
          key: ${{ runner.os }}-${{ hashFiles('**/source') }}

      - name: bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - run: bundle exec middleman build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./documentation/build
